[build]
  command = "npm run build"      # Command to build your project
  publish = "dist"               # Vite output directory

# Optional: only if you use serverless functions
# [functions]
#   directory = "netlify/functions"
